### ISSUE TITLE
Requests being denied a response from browsers

### ISSUE THREAD

**Issue by danielfernandez** [reactor/reactor-ipc#20]
I'm facing a very strange issue with `io.projectreactor.ipc:reactor-netty:0.5.0.M2`.

To be honest, I'm not really sure if the issue is at `reactor-netty` or actually at Netty itself. It's just that I am supposing that, being the Netty version more stable (`4.1.3.Final`), it seems more possible that it is a `reactor-netty` thing. I'm terribly sorry if I'm wrong and this is a Netty thing… I just cannot understand enough what is happening to determine who to blame, and I have to start somewhere 😔 

I have created a test project (Spring Boot-enabled, using the new experimental _Reactive Web_ support), including a README with instructions, here: https://github.com/danielfernandez/test-spring-boot-reactive-netty

The idea is that, when I start this application using `mvn spring-boot:run` and try to access the only controller it's serving –a very, very simple one– using a browser (Chrome, Firefox or Safari) on Mac OS, after some refreshes (normally 2-3), the server starts sending an HTTP response only every two HTTP requests.

I've verified that the requests reach the server (by debugging), and also that there is no HTTP response at all in those cases (by sniffing the network). I've also verified that the HTTP requests look exactly the same when there is response and when there is not. Also, weirdly, I've **not** been able to reproduce this using `curl`, `httpie` or `wget`. Only from browsers.

I've also verified that this does not only happen to me (Mac OS El Capitan 10.11.6). I've seen this happening too on a Mac OS Yosemite machine.

Versions been used:
- `reactor.version`: `3.0.0.RC1`
- `spring.version`: `5.0.0.M1`

**Comment by danielfernandez** [comment]
The issue still persists after updating the sample application (see above) to:
   * `reactor.version`: `3.0.3.BUILD-SNAPSHOT`
   * `spring.version`: `5.0.0.BUILD-SNAPSHOT`

Also, the issue seems not to be MacOS-only, as I've replicated this also in a Windows 10 machine. The environments this has been verified to happen are:
   * Chrome 52, Postman (Chrome-based), Firefox 49 and Safari 9.1.3 on **Mac OS X 10.11 El Capitan** (server + browsers, all local).
   * Chrome 52 and Firefox 49 on **Windows 10** (server + browsers, all local).

But, **important**: in these same machines –actually, without even stopping the netty server–, the issue cannot be replicated if the server is accessed using the external IP address instead of `localhost`. 

So with the same browser, same server instance, `http://localhost:8080` shows the issue, while `http://192.168.0.20:8080` does not.

**Comment by danielfernandez** [comment]
An additional example application to check this behaviour is the *Thymeleaf + Spring Reactive* sandbox application (which I use as a sandbox for creating the Thymeleaf integrations with Spring Web Reactive).

It's here: https://github.com/thymeleaf/thymeleafsandbox-springreactive/tree/nettyissue (note there is a `nettyissue` branch).

It can be built with `mvn -U clean compile spring-boot:run`, and visited at `localhost:8080`.

The interesting part about this app is that the index pages for both Thymeleaf and FreeMarker (at URLs `/`, `/thymeleaf` and `/freemarker`) include a static resource that should be displayed (a logo in PNG). And this fact of including static resources in the returned HTML page seems to force even more the reproducibility of this issue.

Using this `thymeleafsandbox-springreactive` application, I've been able to replicate this even on an **Ubuntu 16** machine with Firefox 48 and Chromium 52.

By the way, I've been reporting this here because, as explained above, I think it might be a `reactor-ipc` issue. If you prefer me to open a JIRA ticket for Spring Web Reactive instead, please just tell. Thanks!

**Comment by rstoyanchev** [comment]
@danielfernandez have you tried switching to one of the other supported servers? It should be a matter of changing the pom only. It would be interesting to see the result with RxNetty and also a different runtime like Tomcat/Jetty.

**Comment by danielfernandez** [comment]
I've created new branches in https://github.com/thymeleaf/thymeleafsandbox-springreactive in order to test other servers. My results:

1. **RxNetty** works OK (branch `rxnetty`). But note bclozel/spring-boot-web-reactive#33.

2. **Undertow** works OK (branch `undertow`).

3. **Tomcat** has some kind of class loader issue (branch `tomcat`):

```
java.lang.ClassNotFoundException: org.thymeleaf.spring4.requestdata.RequestDataValueProcessor4Delegate
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ~[tomcat-embed-core-8.5.5.jar!/:8.5.5]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_66]
	at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_66]
	at org.thymeleaf.spring4.requestdata.RequestDataValueProcessorUtils.<clinit>(RequestDataValueProcessorUtils.java:70) ~[thymeleaf-spring4-3.0.1.RELEASE.jar!/:3.0.1.RELEASE]
```

Interestingly this exception only appears when I execute the app using the maven `spring-boot:run` target or directly using the `java` command, but not when I execute the `Application` class from IntelliJ. Anyway, I will investigate a bit more and report it at JIRA, as it seems some kind of strange interaction between Thymeleaf, the Reactor, Spring Web Reactive and Spring Boot…

Anyway, as I said, when I execute the app using **Tomcat** from IntelliJ and there are no class loader issues, it works OK.

So this does look like an issue in `reactor-ipc`/`reactor-netty`, I suppose.

Also, from bclozel/spring-boot-web-reactive#21 it seems I'm not the only one experiencing this issue…

**Comment by sdeleuze** [comment]
I also confirm this issue that makes for example SSE example from https://github.com/sdeleuze/spring-reactive-playground unusable with Reactor Netty. Other engines are fine.

**Comment by sdeleuze** [comment]
This bug has been fixed in Reactor Netty 0.5.2.RELEASE, since this version now closes HTTP connection after each request. Keep-alive support will be enable again when properly supported.

@smaldini I guess this bug should be moved to https://github.com/reactor/reactor-netty/ and marked as fixed in reactor-netty 0.5.2.RELEASE, isn't it ?

**Comment by danielfernandez** [comment]
So reactor/reactor-netty#4 seems to be the cause for this...

**Comment by danielfernandez** [comment]
I can confirm this seems *fixed* (or worked around ;)) for me now.
